rm(list = ls())
options(stringsAsFactors = F)
source("udf.R")
creDir("data")
creDir("res")
creDir("public")
dataDir = file.path(getwd(),'data')
resDir = file.path(getwd(),'res')
publicDir = file.path(getwd(),'public')
library(mstherm)
control <- system.file("extdata", "demo_project/control.tsv", package="mstherm")
annots <- system.file("extdata", "demo_project/annots.tsv", package="mstherm")
expt <- MSThermExperiment(control, annotations=annots)
expt <- normalize_to_std(expt, "cRAP_ALBU_BOVIN", plot=FALSE)
res <- model_experiment(expt, bootstrap=FALSE, np=2)
# plot single MSThermResult
plot(res$P38707)
# plot all proteins (e.g. to pdf device, one-per-page)
plot(res)
df <- as.data.frame(res)
